### ISSUE TITLE
Error in deployment on VPS and Heroku

### ISSUE THREAD

**Issue by chankitsaini** [YuZaGa/Club-website#1]
`heroku run python manage.py migrate` is giving 
`AssertionError: database connection isn't set to UTC`, I have even downgraded `psycopg2` to earlier version and according to GitHub issues I even upgraded django to latest version, but still in vain.

**Comment by YuZaGa** [comment]
Hi ! I deployed it on Heroku as well and it's working fine at the moment. That said I deployed it almost a year back and haven't made any changes to it. The issue in my opinion should be related to bumping up psycopg2(It gave issues even initially :/). 
[https://stackoverflow.com/questions/68024060/assertionerror-database-connection-isnt-set-to-utc](url)
Try downgrading to the version mentioned here. If it still doesn't ,try USE_TZ = False (a workaround). Hit me up if it's still giving issues.

**Comment by chankitsaini** [comment]
> Hi ! I deployed it on Heroku as well and it's working fine at the moment. That said I deployed it almost a year back and haven't made any changes to it. The issue in my opinion should be related to bumping up psycopg2(It gave issues even initially :/). [https://stackoverflow.com/questions/68024060/assertionerror-database-connection-isnt-set-to-utc](url) Try downgrading to the version mentioned here. If it still doesn't ,try USE_TZ = False (a workaround). Hit me up if it's still giving issues.

I got some issues and questions, how can I contact you regarding that?

**Comment by YuZaGa** [comment]
Ping me on Linkedin [https://www.linkedin.com/in/yumn-gauhar/](url)
